version: "3.6"

networks:
  rabbitmq_net:
    name: rabbitmq_net
    driver: bridge
      
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.11.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=test-vhost